/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShareV2PayloadRouteImport } from './routes/share.v2.$payload'
import { Route as ShareImageV2PayloadRouteImport } from './routes/share-image.v2.$payload'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareV2PayloadRoute = ShareV2PayloadRouteImport.update({
  id: '/share/v2/$payload',
  path: '/share/v2/$payload',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareImageV2PayloadRoute = ShareImageV2PayloadRouteImport.update({
  id: '/share-image/v2/$payload',
  path: '/share-image/v2/$payload',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/share-image/v2/$payload': typeof ShareImageV2PayloadRoute
  '/share/v2/$payload': typeof ShareV2PayloadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/share-image/v2/$payload': typeof ShareImageV2PayloadRoute
  '/share/v2/$payload': typeof ShareV2PayloadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/share-image/v2/$payload': typeof ShareImageV2PayloadRoute
  '/share/v2/$payload': typeof ShareV2PayloadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/share-image/v2/$payload' | '/share/v2/$payload'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/share-image/v2/$payload' | '/share/v2/$payload'
  id: '__root__' | '/' | '/share-image/v2/$payload' | '/share/v2/$payload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShareImageV2PayloadRoute: typeof ShareImageV2PayloadRoute
  ShareV2PayloadRoute: typeof ShareV2PayloadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/v2/$payload': {
      id: '/share/v2/$payload'
      path: '/share/v2/$payload'
      fullPath: '/share/v2/$payload'
      preLoaderRoute: typeof ShareV2PayloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share-image/v2/$payload': {
      id: '/share-image/v2/$payload'
      path: '/share-image/v2/$payload'
      fullPath: '/share-image/v2/$payload'
      preLoaderRoute: typeof ShareImageV2PayloadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShareImageV2PayloadRoute: ShareImageV2PayloadRoute,
  ShareV2PayloadRoute: ShareV2PayloadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
